### ISSUE TITLE
Access storybook on heroku

### ISSUE THREAD

**Issue by pchr-srf** [aperkaz/storybook-on-heroku#1]
Thanks for the procfile! I'm wondering how to access the storybook on the build, though.
I copied your Procfile and deployed my project to heroku, but I can only access the "default page", which is nothing in my case.
Locally I can access the storybook on localhost:9009/ but not on heroku. How did you access yours?

**Comment by emaxees** [comment]
Hi @pchr-srf, did you find a solution for that?. Thank you!

**Comment by pchr-srf** [comment]
Nope, unfortunately not. I also asked the question on SO: https://stackoverflow.com/questions/56866780/access-storybook-on-create-react-app-deployed-to-heroku

But luckily for me it was just a prototype and storybook on heroku was not needed for anything :)

**Comment by texyh** [comment]
i need a solution to this please

**Comment by aperkaz** [comment]
Hi @pchr-srf  @emaxees and @texyh ,

I had the time to look into this and fixed it. 

Modify `package.json` and add command:
```
"heroku-build": "build-storybook -s public",
```

Modify the `Procfile` to: 
```
web: http-server storybook-static
```

You can check all the changes in the repo 🙂

**Comment by LePhil** [comment]
Thank you very much! Will try it out after the holidays :)
