### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by drewbaker** [aperkaz/storybook-on-heroku#6]
I tried this and the only thing that is displayed is `Invalid Host header`. I have nothing set in my Heroku Config Vars. Do I need to define something there?

**Comment by drewbaker** [comment]
Just to clarify, I've added the following to my `package.json` file

In scripts I added:
```
"scripts": {
        "build-storybook": "build-storybook -s public",
        "heroku-build": "build-storybook -s public"
    }
```

Then in dependencies I added:
```
    "dependencies": {
        "http-serve": "^1.0.1",
        "http-server": "^0.11.1"
    }
```

And my `Procfile` has `web: http-server storybook-static` in it.

**Comment by drewbaker** [comment]
OK for future generations, this is how I solved it:

FYI I am using the Vue version of Storybook, but this really should be the same for all flavors of Storybook.

You do not need to add anything extra to your `package.json` file, other than:
```
    "engines": {
        "node": "10.13.0"
    },
    "scripts": {
        "heroku-postbuild": "build-storybook -s public"
    }
```

NOTE: The node version doesn't have to be that, whatever you need and that Storybook requires is fine.

Then you need to create a `static.json` in your root, and add this to it:
```
{
    "root": "storybook-static",
    "clean_urls": true,
    "routes": {
        "/**": "index.html"
    }
}
```

Then in Heroku, you need to make sure you have the `heroku/nodejs` and `https://github.com/heroku/heroku-buildpack-static` buildpacks installed. You can do this through the UI on their site in the Settings panel, or via the terminal using:
```
heroku buildpacks:add heroku/nodejs
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-static
```

And that is it, no need for `http-serve` or `http-server`. You are now serving static files from Heroku!

**Comment by aperkaz** [comment]
Thanks for the clarification @drewbaker, ill update the docs when I have some extra time 🙂
